### ISSUE TITLE
Headquarters popup comes with with noting in it.

### ISSUE THREAD

**Issue by Voodles12** [LecksC/ASOR_Bugs#110]
Pops up like the QRF one but there's nothing in it

**Comment by Heilidhe** [comment]
Might need to check this out @suitsy ... think you added adv hint somewhere recently? Might be using the same classname or something. Will have a look too tomorrow. Does the QRF one actually appear with text?

**Comment by Voodles12** [comment]
Yeah QRF one Appears fine there's something else that's been added that's popping up about 15 times at mission start, then randomly throughout opp

**Comment by suitsy** [comment]
It comes up with "Intel has been updated" 
Might be the intel setup? I havent added an adv hint in months.

**Comment by Instant-Muffin** [comment]
My Intel shouldn't be doing anything. Vanilla Intel maybe? Only started on Wednesday and only changes before that was asor_weapons and factions

**Comment by suitsy** [comment]
see if it does it on other missions, might be just an odd setup? havent had it in the editor myself

**Comment by Heilidhe** [comment]
Uh yeah it sounds like objectives module. Think its a commit i wasn’t ready to add but was put in for new campaign. Weird that its doing it now and not before. Will fix tonight.

My bad boys, false accusations, thats a six pack each, my shout..
