### ISSUE TITLE
[CLOSED] AE: Mortar Module

### ISSUE THREAD

**Issue by LecksC** [LecksC/ASOR_Bugs#14]
<a href="https://github.com/suitsy"><img src="https://avatars3.githubusercontent.com/u/13358761?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [suitsy](https://github.com/suitsy)**
_Thursday Dec 03, 2015 at 04:48 GMT_
_Originally opened as https://github.com/LecksC/ASOR/issues/9_

----

Radius
Frequency
Not on Players / Random
Stop when !alive ??

**Comment by LecksC** [comment]
<a href="https://github.com/suitsy"><img src="https://avatars3.githubusercontent.com/u/13358761?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [suitsy](https://github.com/suitsy)**
_Monday Mar 06, 2017 at 23:28 GMT_

----

Added version 2.5

**Comment by suitsy** [comment]
Done.
