### ISSUE TITLE
Enable Zone Updates

### ISSUE THREAD

**Issue by LecksC** [LecksC/ASOR_Bugs#16]
<a href="https://github.com/suitsy"><img src="https://avatars3.githubusercontent.com/u/13358761?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [suitsy](https://github.com/suitsy)**
_Monday Mar 06, 2017 at 23:32 GMT_
_Originally opened as https://github.com/LecksC/ASOR/issues/11_

----

1. Ensure Zones are linkable to multiple Enable Zones 
2. Set Zones to be disable when zone set to suspended with enable zone linked

**Comment by suitsy** [comment]
Replaced Enable Zone with Control Zone, Closing.
