### ISSUE TITLE
Task Module

### ISSUE THREAD

**Issue by LecksC** [LecksC/ASOR_Bugs#17]
<a href="https://github.com/suitsy"><img src="https://avatars3.githubusercontent.com/u/13358761?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [suitsy](https://github.com/suitsy)**
_Monday Mar 06, 2017 at 23:32 GMT_
_Originally opened as https://github.com/LecksC/ASOR/issues/12_

----

1. Add option to delete unit on last waypoint.

**Comment by suitsy** [comment]
No longer required with Dynamic Simulation. Closing.
