### ISSUE TITLE
Add Airdrop Module

### ISSUE THREAD

**Issue by LecksC** [LecksC/ASOR_Bugs#18]
<a href="https://github.com/suitsy"><img src="https://avatars3.githubusercontent.com/u/13358761?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [suitsy](https://github.com/suitsy)**
_Monday Mar 06, 2017 at 23:33 GMT_
_Originally opened as https://github.com/LecksC/ASOR/issues/13_

----

1. Add Airdrop Module

**Comment by suitsy** [comment]
Make cargo and aircraft to deploy it linkable to module.

**Comment by suitsy** [comment]
Made this an AE Menu thing as well as airstrikes. Done.
