### ISSUE TITLE
Artillery Module Updates

### ISSUE THREAD

**Issue by LecksC** [LecksC/ASOR_Bugs#19]
<a href="https://github.com/suitsy"><img src="https://avatars3.githubusercontent.com/u/13358761?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [suitsy](https://github.com/suitsy)**
_Monday Mar 06, 2017 at 23:34 GMT_
_Originally opened as https://github.com/LecksC/ASOR/issues/14_

----

1. - [ ] Add option to hold fire on spawn
2. - [ ] Create function to fire.
3. - [ ] Add ability to link Position modules for targeting off zone activation
4. - [ ] Add ability to have a random barrage
5. - [ ] Add ability to have a random delay

**Comment by LecksC** [comment]
<a href="https://github.com/suitsy"><img src="https://avatars3.githubusercontent.com/u/13358761?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [suitsy](https://github.com/suitsy)**
_Sunday Mar 19, 2017 at 07:10 GMT_

----

6. - [ ] Update so second time it loads it only does the firing not spawning.

**Comment by suitsy** [comment]
repeat function doesnt seem to be working, probably dont use it and just have the zone re-enable option without spawning the units again, just does the firing again
- [x] add variable to zone aeArtilleryCreated

**Comment by suitsy** [comment]
Edited to make the createArtillery function only spawn the units once, should be able reset the zone linked to the art module and will only fire arty the second time not spawn them again.
- [ ] tested no double spawning, fires only second load
- [ ] test if linking multiple zones will work

**Comment by suitsy** [comment]
Tested - Done
