### ISSUE TITLE
Update Spectator

### ISSUE THREAD

**Issue by LecksC** [LecksC/ASOR_Bugs#23]
<a href="https://github.com/suitsy"><img src="https://avatars3.githubusercontent.com/u/13358761?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [suitsy](https://github.com/suitsy)**
_Tuesday Mar 07, 2017 at 00:41 GMT_
_Originally opened as https://github.com/LecksC/ASOR/issues/18_

----

Updated spectator to new ingame one.

**Comment by LecksC** [comment]
<a href="https://github.com/suitsy"><img src="https://avatars3.githubusercontent.com/u/13358761?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [suitsy](https://github.com/suitsy)**
_Tuesday Mar 07, 2017 at 00:41 GMT_

----

Will need to update all signs with spectator.

**Comment by LecksC** [comment]
<a href="https://github.com/LecksC"><img src="https://avatars3.githubusercontent.com/u/13845562?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [LecksC](https://github.com/LecksC)**
_Monday Mar 20, 2017 at 02:27 GMT_

----

Could also change the function that's on the signs so it just calls the ACE spectator one to save some work.

**Comment by LecksC** [comment]
<a href="https://github.com/suitsy"><img src="https://avatars3.githubusercontent.com/u/13358761?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [suitsy](https://github.com/suitsy)**
_Monday Mar 20, 2017 at 04:04 GMT_

----

Yeah thats what I meant. Is the spectator vanilla or ace? Is there even a vanilla one? Whatever one is used for PVP anyway, has same capability as our old one but is heaps smother, better looking and error free.

Not sure how TFAR handles it, @Instant-Muffin can u answer that?

**Comment by Instant-Muffin** [comment]
PvP is ace. Vanilla has one now but no idea how it works.

**Comment by LecksC** [comment]
<a href="https://github.com/Instant-Muffin"><img src="https://avatars3.githubusercontent.com/u/22660486?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Instant-Muffin](https://github.com/Instant-Muffin)**
Switched the spectator but needs testing on the server.

**Comment by LecksC** [comment]
Sounds good.. is it set so you can only first person spectate friendlies (preferably just players too I guess)?

If so, should we put this on for Sunday (and/or PvP)?

**Comment by Instant-Muffin** [comment]
Will wait until it can be tested properly after Sunday. Not needed for tonight, I don't use the mission module. Players can spectate playable units on sides they are friendly to.

**Comment by suitsy** [comment]
We tested successfully but on respawn ppl spawned by were still stuck in spectator. Need to test that setting setplayerrespawntime to 0 is what causes that issue.

**Comment by LecksC** [comment]
An instant death/respawn would like cause it. We added a 1 second delay after dieing because it seemed to be putting you in spectator before you hit the ground. The order it would call it is like
1. die script > sleep 1
2. come alive script > close spectator
3. sleep ends - open specatator.

Maybe an extra 'alive _unit' check after the sleep would work around it. Or minimum 2 second respawn time (but that can't be enforced automatically).

**Comment by suitsy** [comment]
When that force respawn function is made will make that 2secs rather than a flay 0 to allow for this too then.

**Comment by suitsy** [comment]
The spawn bug wasnt an issue, think setting 'setplayerrespawntime' to 0 was the issue. It seems now the respawn time needs to be set to the actual respawn time though with this spectator, has people in spectator for over 15 mins on sunday.

I think @LecksC set this to the correct respawn time to get it to work right.

Different Issue
- some people not going into or taking a long time to go into spectator (possibly server lag?)

**Comment by MitchDrage** [comment]
Looks like spectators also have free look enabled. We will need to disable that too.

**Comment by suitsy** [comment]
the free look was because i forgot to tell mission makers to put module down and it just used default settings

**Comment by Instant-Muffin** [comment]
A fix for respawn times of 0 was pushed a few days ago, along with a 2 second delay after death before it opens so it's not so sudden. No progress on saving the settings though. Will likely leave it until we start removing the other ACE modules.

**Comment by LecksC** [comment]
The fix @Instant-Muffin pushed was on the repo last night. Did it fix that insta-spectator thing?

**Comment by suitsy** [comment]
@lecks @Instant-Muffin yeah spec was fine except for the settings.

**Comment by LecksC** [comment]
Ok, closing this and opening the ticket for server-side ACE settings
