### ISSUE TITLE
Fatigue System broken in 1.68

### ISSUE THREAD

**Issue by LecksC** [LecksC/ASOR_Bugs#26]
<a href="https://github.com/LecksC"><img src="https://avatars3.githubusercontent.com/u/13845562?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [LecksC](https://github.com/LecksC)**
_Monday Mar 20, 2017 at 03:14 GMT_
_Originally opened as https://github.com/LecksC/ASOR/issues/21_

----

Apparently fatigue isn't working. Couldn't see a stamina bar, and ReaperSmurf reported he could run full speed despite carrying 55kg.

**Comment by LecksC** [comment]
<a href="https://github.com/suitsy"><img src="https://avatars3.githubusercontent.com/u/13358761?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [suitsy](https://github.com/suitsy)**
_Monday Mar 20, 2017 at 12:38 GMT_

----

Must have changed something with fatigue, could try delete asor_fatigue and adding ace fatigue back in see if ace has a fix.

**Comment by LecksC** [comment]
<a href="https://github.com/LecksC"><img src="https://avatars3.githubusercontent.com/u/13845562?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [LecksC](https://github.com/LecksC)**
_Wednesday Mar 22, 2017 at 06:41 GMT_

----

ace_advanced_fatigue is now on the repo, and asor_fatigue has been removed.

Seems to still broken.

putting this in debug console fixed it:

player enableFatigue true;
player enableStamina true;

So it must be set disabled somewhere? Difficulty settings?

It seemed harsh when using these commands, but not sure (45kg couldn't sprint at all.. around 30 was ok).

**Comment by suitsy** [comment]
added ace_adv_fatigue and tweaked the settings for it in the ace_server.pbo config file (userconfig) on server

**Comment by suitsy** [comment]
Fatigue settings ok for now going to leave it. Closing.
