### ISSUE TITLE
Create Vehicle & Wave Para Function

### ISSUE THREAD

**Issue by LecksC** [LecksC/ASOR_Bugs#27]
<a href="https://github.com/suitsy"><img src="https://avatars3.githubusercontent.com/u/13358761?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [suitsy](https://github.com/suitsy)**
_Monday Mar 20, 2017 at 12:05 GMT_
_Originally opened as https://github.com/LecksC/ASOR/issues/22_

----

For para of vehicles and infantry.

Including multi wave para inserts

**Comment by suitsy** [comment]
Basic Para Setup is working.

**Comment by suitsy** [comment]
TODO:
- Remove the ASOR Para functions and replace with a command that initiates all setup SQUAD para drops.
- Add a Wave insertion capability so all teams can be inserted in a timed wave
- Add a QRF function so any QRF can re-para until MSV QRF is setup
- Remove need to have someone in the vehicle you want to para;
- Add action to vehicles to "Rig Vehicle for Para" to add it to the SQUADS para drop.
- Change height of vehicle chute deploy *2 of current.
- Check the directions and fix so the drop location is the start of the para drop (vehicles first) and units are spread from the drop location in the direction of the approach.
- Make the approach direction GLOBAL
- Use something else other than the stupid whiteboard for the para initiation and setup
- Colour the icons if possible to indicate initiate (jewfishy syndrome) 
- Maybe add a sub menu for initiate like a "WARNING: Confirm Para Insertion Ready".

**Comment by suitsy** [comment]
- ability to para drop supplies in

**Comment by suitsy** [comment]
- added para drop for entire squad (squad members must be with 30m of stand)
- added qrf para drop option (added to qrf board too)
- added drop wave (not 100% yet, drops all squads in 2min intervals)
- added drop all squads (initiates all setup squads)
- added "Rigg for Para Drop" to vehicles so someone does not have to be in veh anymore
- vehicles must be within 100m of sign (wont redrop)
- made height selector, direction, smoke all global for all drops
- made a clearer menu (thanks lecks)


STILL TO DO / FIX
- set qrf para drop to be disabled once MSV or a command is set.
- fix vehicle drop location (current on or too close to players)
- add custom icons
- add ability to drop supplies, 
- fix all squads and wave para drop
- fix QRF initiating fade to black on all players
- add ability to set wave timer

**Comment by suitsy** [comment]
Re-wrote entire para functions with LecksBot SQF Checker 3.7.5. Should fix some issues and allow for better use with other future ideas.

Possible Fixed but needs testing:
add ability to drop supplies,
fix all squads and wave para drop
fix QRF initiating fade to black on all players
add ability to set wave timer

TO-DO:
set qrf para drop to be disabled once MSV or a command is set.
fix vehicle drop location (current on or too close to players)
add custom icons

**Comment by MitchDrage** [comment]
I can help with the icons. Do you have something in mind?

**Comment by suitsy** [comment]
I believe this has all been updated and is awaiting testing?

**Comment by suitsy** [comment]
- [x] Confirmed individual squad para drops work
- [ ] Confirmed ALL para drop works
- [x] Confirmed QRF para drop works (to main LZ)
- [x] Confirmed vehicle para drop works

**Comment by suitsy** [comment]
Think we just need to get the ALL para drop working and this is good to close.

**Comment by suitsy** [comment]
Done.
