### ISSUE TITLE
ASOR Factions (Units Re-do)

### ISSUE THREAD

**Issue by LecksC** [LecksC/ASOR_Bugs#29]
<a href="https://github.com/Heilidhe"><img src="https://avatars3.githubusercontent.com/u/19974989?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Heilidhe](https://github.com/Heilidhe)**
_Monday Mar 20, 2017 at 13:01 GMT_
_Originally opened as https://github.com/LecksC/ASOR/issues/24_

----

Merge all wanted Units into asor_factions.

Work:
folder structure (factions + configs)
files & presets (uniforms, weapons etc)

THINGS TO TEST
Unit Ammo Counts
AT Rockets Carried

Healy loses his #dev virginity. Understands what 'not understanding' means.

**Comment by LecksC** [comment]
<a href="https://github.com/Heilidhe"><img src="https://avatars3.githubusercontent.com/u/19974989?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Heilidhe](https://github.com/Heilidhe)**
_Tuesday Mar 21, 2017 at 03:02 GMT_

----

https://codeshare.io/5MkJBn

**Comment by suitsy** [comment]
got this almost to testing phase, as part of this I am setting up and cleaning up:
asor_helmets
asor_vests
asor_uniforms
asor_backpacks
potentially also:
asor_facewear

Any factions with custom textured gear will be able to use these instead of modifying asor_factions configs for each one. Dont expect many to have custom textured gear in any case.

**Comment by LecksC** [comment]
@suitsy see https://github.com/LecksC/ASOR/commit/1097a9355ca23c87b34c8a4cd96937ef929a803b

I had to revert your change to basic_defines.hpp because it broke asorgs (and likely others). Suggest either putting it in a different .hpp that will only be used with configs, or making a copy of basic_defines.hpp in asor_main to use in configs including these ones.

**Comment by suitsy** [comment]
Yeah right, i had a basic_defines_A3 i was using and i compared it to the common one and seemed exactly the same couple of differences so copied what wasnt in there in.  Maybe i left a double up, should not have made a difference I would have thought. 

I dont really use the defines anyway might just leave it out. Cheers Lecks hopefully this is the cause of some of the issues.

**Comment by suitsy** [comment]
Majority of units done now, going to need some testing for each faction.
- [ ] Loadouts tested
- [ ] uniforms and kit tested
- [ ] vehicles tested
- [ ] gear selector for each faction correct
- [ ] vehicle selector correct for each faction

**Comment by suitsy** [comment]
- [ ] add facewear

**Comment by suitsy** [comment]
- [ ] add pla
- [ ] add pla sf
- [ ] add sasr uk
- [ ] add weimar union 
- [ ] add weimar union sf
- [ ] add middle eastern factions back in

**Comment by suitsy** [comment]
Done - asor_factions
