### ISSUE TITLE
Bushmaster ACE Interact Broken

### ISSUE THREAD

**Issue by LecksC** [LecksC/ASOR_Bugs#30]
<a href="https://github.com/Heilidhe"><img src="https://avatars3.githubusercontent.com/u/19974989?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Heilidhe](https://github.com/Heilidhe)**
_Wednesday Mar 22, 2017 at 08:25 GMT_
_Originally opened as https://github.com/LecksC/ASOR/issues/25_

----

MSV bushmasters are the only bushmasters working allowing ACE interact. ECM, TRANSPORT and COMMAND variants have no interact. Will look further to see if its an issue we can resolve.

**Comment by LecksC** [comment]
<a href="https://github.com/LecksC"><img src="https://avatars3.githubusercontent.com/u/13845562?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [LecksC](https://github.com/LecksC)**
_Wednesday Mar 22, 2017 at 15:09 GMT_

----

This issue was moved to LecksC/ASOR_Bugs#3

**Comment by MitchDrage** [comment]
What are we looking to do with ace_interact, is it to change wheels, etc?

**Comment by LecksC** [comment]
Yeah, mainly cargo. You can load stuff into it but can't unload because the interact doesn't show up.

**Comment by suitsy** [comment]
ACE Interact was working on bushmasters and lavs on the weekend, is this still an issue?

**Comment by LecksC** [comment]
I think the para drop stuff might have accidentally fixed this.

**Comment by suitsy** [comment]
Para stuff good for something then. Will close, re-open if it comes up again.
