### ISSUE TITLE
More rockets & Medical in ammo boxes?

### ISSUE THREAD

**Issue by LecksC** [LecksC/ASOR_Bugs#31]
Pretty much every time we're asked to get ammo, it comes with a 'special request' for extra rockets, which generally causes a delay.

Think we should just add more launchers, etc to the ammo box? (or make an extra one with more).

Also, currently have Ammo (air transport only) and Medical (vehicle transport only). Might make it quicker to have 4 (air ammo, vehicle ammo, air medical, vehicle medical), or have medical + ammo in both. Medical-only drops are pretty much non existent at the moment.

**Comment by Heilidhe** [comment]
Yeah, in agreement. Where are the files currently for this? Can look at doing this up myself.

**Comment by suitsy** [comment]
Ammo crates are located in asor-ammo. 
I believe ammo crates already have medical supplies, the medical only ones have more thats all and are for a medical only request. I thought I did do both air and veh transportable versions for each will need to check that out, maybe they are not coming up in the spawner for some reason?

1. Add more rocket to ammo
2. Add AA rockets to ammo
3. Check medical supplies in all crates
4. Ensure we have each ammo box in versions of:
4a. Air Transportable
4b. Vehicle Transportable

**Comment by Heilidhe** [comment]
Added AA, AT, Disposable HEAT's, Medical Check.

**Comment by Heilidhe** [comment]
Reopened Issue:

- DEFSUPP Crate
- Add More IV's.
Trial of both.

**Comment by suitsy** [comment]
I dont think we need a AT crate, its covered plenty in the ammo resupp especially with the increase in amount of rockets, dont see much point to taking just rockets in.

**Comment by Heilidhe** [comment]
Rgr. No AT crate.

**Comment by suitsy** [comment]
This is done yeah just needs to go on repo yeah @Heilidhe ?

**Comment by LecksC** [comment]
I think it's on the repo?

**Comment by Heilidhe** [comment]
Yeah sorry fellas. Was done last Sunday. Needs verification, Testing after Wed/Sun OP - Will Close this, and Re-Open if issues. 

Might need to Re-Open another with whatever is going on with the Supply Selector at MSV QRF. Annoying how you need to load a preset - not sure why you can't just have a big and small version of ammo and medical- would be good to change if possible imo.
