### ISSUE TITLE
Make ASOR Signs Placeable

### ISSUE THREAD

**Issue by suitsy** [LecksC/ASOR_Bugs#34]
Make Main and QRF signs objects with ace menus so they are place-able in 3DEN.

**Comment by suitsy** [comment]
@synddd this might be a good one if your looking for something to have a crack at. Its basic config for action menus and the new asor_objects folder is created and has the para sign as a template essentially.

Just offering this up as you mentioned helping out with something not to complicated. This is needed for the new campaign. Would be an 
ASOR Main Sign
ASOR QRF Sign (main sign no gear selector)

Might be some other signs required not sure will have to think about that one.

**Comment by MitchDrage** [comment]
Ack, I'll work on it.

**Comment by MitchDrage** [comment]
Uploaded and on repo. Closing.
