### ISSUE TITLE
ASOREdit Multiple Static Spawning

### ISSUE THREAD

**Issue by Heilidhe** [LecksC/ASOR_Bugs#36]
ASOREdit seems to spawn Multiple AI and/or multiple Static Weapons sometimes. Usually can be recreated by removing default units and replacing them with units of another faction.

**Comment by LecksC** [comment]
Hmm not sure how the reproduction makes sense. The zones don't 'know' anything about the synced units until the mission is launching. 

Does it happen without the ASOREdit main module down? (are they duplicating in 3DEN).

A simple single zone/single unit reproduction would be awesome if anyone has time. Might be able to spot the issue in the mission SQM then (not gonna try with FTX).

**Comment by LecksC** [comment]
> **ReaperSmurf:** It is grouping the HMG to another unit (another HMG on my scenario).
> I ungrouped them from each other.
> Then I removed the sync to the zone altogether, then resynced to the zone from the gun icon, not the unit/soldier icon.

Maybe this is actually normal? I don't think multiple static weapons in a group would be supported? Seem to remember it being designed so static weapons should be their own group.

**Comment by Heilidhe** [comment]
Not actually sure. Haven't had time to do testing, but will look into and do some tests. Will leave issue open, and tag 'Needs Testing/Verification'.

**Comment by Heilidhe** [comment]
## Result
This issue seems to be consistent and persistent each time a static emplacement is spawned (at least for me). At first, thought it was an issue only on the FTX, but upon a new mission, it does the same.

It is re-creatable, by placing a static weapon and placing a unit onto the weapon and linking him to a zone.

It will always happen regardless of:
- Whether the Static was spawned with crew or not.
- Whether the Static is of the same faction or not.
- Whether the unit was synced (to zone) before being placed in the static, or after.

Of course, this issue is not prevalent when a static is spawned with its default crew.
It seems replacing a crew even with units from the same faction, still creates this issue. 

I'm not sure this is an issue easily resolved, as it seems to be a complete mystery as to why its happening. There are very few cases where it matters, as 90% of the time, placing statics usually results in keeping the default crew (of that faction).

**Comment by suitsy** [comment]
Havent seen this issue recently. Closing.
