### ISSUE TITLE
Reminder: Setup GS for ASOR Units.

### ISSUE THREAD

**Issue by Heilidhe** [LecksC/ASOR_Bugs#41]
Reminder to add Faction configs for new units under the ASOR Units redo., for the gear selector.
- All need to be faction specific
- 12 or more factions etc

**Comment by Heilidhe** [comment]
There will be new faction names and new gear names for everything.
New Unit names.

Overhaul to Blacklist layout.

**Comment by suitsy** [comment]
I have created a new blacklist template and started working on most of the new factions, need to run you through it @Heilidhe 

Generally though the blacklist is now in the asor_factions mod, each faction has a gear_blacklist.hpp that sets up their blacklist. In asor_gear_selector their will be a global blacklist that pretty much blocks everything and the factions ones allow the kit for them.

**Comment by Heilidhe** [comment]
Rgr. Can't yet see this on Master, but sounds easy enough to understand.

**Comment by suitsy** [comment]
@Heilidhe pushed to repo

**Comment by suitsy** [comment]
Going to change GS to whitelist so only items listed in the factions gear_list.hpp will be available.

Perhaps we could do it like 
ALL LIST -> FACTION LIST -> GROUP LIST
so would be
ALL -> Berkovetus -> BNG
or
ALL -> Russia -> Zaslon
etc

**Comment by suitsy** [comment]
Whitelist is all setup for all factions (except PLA and any faction not finalised gear wise). Still working on function/script to extract weapon attachments as this will need to be done manually in the whitelist.

Whitelist has 3 levels
ALL LIST - Located in asor_gear_selector
GROUP LIST - Located in asor_factions/factions/side/group_folder   ie. Russian
FACTION LIST - Located in asor_factions/factions/side/group/faction_folder  

- [x] weapon attachment function/script setup
- [x] whitelists good to go

**Comment by suitsy** [comment]
Other than minor adjustments per faction the whitelist is functioning and gtg, closing ticket.
