### ISSUE TITLE
Add function to enable a forced respawn

### ISSUE THREAD

**Issue by suitsy** [LecksC/ASOR_Bugs#44]
Add to @ASOR enable it through AE menu also.

- setplayerrespawntime 0; 
- setplayerrespawntime 1e10;

**Comment by MitchDrage** [comment]
Lecks has created the function:
asor_common/functions/respawn/fn_RespawnNow.sqf
ASORRespawn_fnc_RespawnNow

**Comment by suitsy** [comment]
This is done but was broken, have since fixed but not testing on server, awaiting next AE update.

**Comment by suitsy** [comment]
AE Menu -> Tools => force QRF respawn confirmed working, Done.
