### ISSUE TITLE
AE Menu Forced Respawn Option

### ISSUE THREAD

**Issue by suitsy** [LecksC/ASOR_Bugs#45]
Add a forced respawn command to the AE Menu

Related function: https://github.com/LecksC/ASOR_Bugs/issues/44

**Comment by suitsy** [comment]
Add a Update Curator to AE Menu

**Comment by LecksC** [comment]
Might be able to make 'Update Curator' an ace zeus action instead? (I think those exist)

**Comment by suitsy** [comment]
added to AE menu, not tested yet forgot to check it last op.

**Comment by suitsy** [comment]
double up - Done
