### ISSUE TITLE
Bodybags at QRF

### ISSUE THREAD

**Issue by suitsy** [LecksC/ASOR_Bugs#47]
Add bodybags near the QRF point for each death of a player during the op. 

- make it a module to put down so mission makers can set the location
- need to make it so they line up neatly, like a grid

**Comment by Heilidhe** [comment]
Working on this now.

**Comment by suitsy** [comment]
@LecksC @Heilidhe didnt we have this pretty much sorted?

**Comment by LecksC** [comment]
I wrote a script that did it in the debug console, but the pastebin link expired. You still got the code @Heilidhe ?

**Comment by suitsy** [comment]
added bodybag module to AE
uses lecks script to spawn body bags for each player death at module location
