### ISSUE TITLE
MSB & MSC

### ISSUE THREAD

**Issue by Heilidhe** [LecksC/ASOR_Bugs#48]
Backpack which allows squads to set a safe-house and spawn point from a deployed backpack. 

Idea:
- Run Script to create marker once backpack is deployed (Could be a selectable option in backpack?).
- Sets position to ALPHA Spawn point or Safe-house etc
- Needs to revert old spawnpoint back to QRF perhaps before a new one is set.

**Comment by Heilidhe** [comment]
## MSB & MSC

Mobile support Backpack - Mobile Support Crate (Names could change).
- Now to be moved to an asor_logistics @Addon. 

## Stuck with Inheritance Issue
- Will soon continue to figure out adding Ace Action to Config.

**Comment by Heilidhe** [comment]
Backpack won't accept ACE Interact. Will need to think of another method for Squads to set their spawn point (another object or perhaps self interact option that can be turned on only in the mission module perhaps).

**Comment by suitsy** [comment]
What about some kind of object if they have it on them they can set the safehouse, aka condition of self interact menu is you need the item. The item has a cost like weight in order to take it so that way everyone cant take one.

**Comment by Heilidhe** [comment]
Yeah not bad idea, will look into it.

**Comment by Heilidhe** [comment]
MSB (Mobile Support Backpacks) has now been designated as the 'Safehouse' project, taken on board by suits. 

Mobile support crates will move to asor_logistics. 
Closed.
