### ISSUE TITLE
Ace interact with Razorwire Bug

### ISSUE THREAD

**Issue by Brannac** [LecksC/ASOR_Bugs#49]
Had an issue on Sunday 2nd of April when EOD wasn't able to interact with the razor wire to cut it and was informed that it has happened before. Not sure if it was OP specific or maybe a bug has arisen.

**Comment by Heilidhe** [comment]
Will check this out. Pretty sure there are two types of RazorWire - Ones that can be cut and ones that can't. Also possibility of ACE Actions being disabled due to someone making it a 'simple object'.

**Comment by Heilidhe** [comment]
Two types of Razor Wire - Vanilla "Land_Razorwire_F" and one from CUP Terrains "Fort_RazorWire".

The Latter is not interactable in ACE. Could perhaps fix this in the future perhaps in asor_fixes, but would probably be easier for mission makers to place the correct wire though.

Thanks for Mention Brannac. Will remind mission makers.

*Closed With Verification*
