### ISSUE TITLE
MSV - New Campaign

### ISSUE THREAD

**Issue by Heilidhe** [LecksC/ASOR_Bugs#50]
*No Spoilers*

MSV ability needs to be added to any of the chosen vehicles, in the next campaign for each faction.
Object compatibility should be fine regardless of faction.

**Comment by Heilidhe** [comment]
Vehicle Base;
rhs_gaz66_r142_msv

**Comment by Heilidhe** [comment]
## Gaz66_MSV

- [x] Completed Framework For File structure (Func, Config)
- [x] Completed Sites for Gaz

**Comment by suitsy** [comment]
- [ ] Change lighting on the MSV to red light

**Comment by Heilidhe** [comment]
## Gazz66

Gazz66 R142 L-MSV's (Logistics - Mobile Support Vehicles) were added to all four Russian factions, capable of completing QRF Logistics operations. 

C-MSV (Combat - Mobile Support Vehicles) and J-MSV (Joint - Mobile Support Vehicles) will be added soon to complete Fire Support requirements (mortars etc).

**Comment by suitsy** [comment]
Make sure any MSV's are available to all factions for the side that uses them.
Added vehicle whitelist that applies to all factions under a group - ie all Russian factions
https://github.com/LecksC/ASOR/blob/master/asor_factions/factions/opfor/russia/all_groups_vehicles.hpp

**Comment by suitsy** [comment]
What do we need to do about the bug with the GAZ. Do you think we should just change a single template for all MSV's to one that works with all or do you want to go down the path of having multiple templates?

**Comment by Heilidhe** [comment]
I believe I've fixed it by just changing the template a bit. Will test on server soon. Currently templates are singular to vehicles, but are mostly the same because of Categories (Logistics MSV, Combat MSV etc). I wouldn't like to lock of the option of variation.

**Comment by Heilidhe** [comment]
## Gaz66 
Added for Blufor

## M977A4
Added for Blufor

## TIGR CSV
Added for Opfor

## M1083A1P2
Added for Blufor (Varcolac)
