### ISSUE TITLE
Spawn Flying

### ISSUE THREAD

**Issue by suitsy** [LecksC/ASOR_Bugs#51]
Cant spawn units flying, broken.

Attempted to use bis createVehicle with "FLY" doesnt seem to work, will createVehicle and add velocity manually instead.

**Comment by MitchDrage** [comment]
I found a post talked about the FLY value being broken. It's an old post, but it suggested feeding the function as an array using getMarkerPos:
http://www.armaholic.com/forums.php?m=posts&q=24018

This worked for me:
[([getPos player select 0, getpos player select 1, 500]), (random 360), "O_Heli_Attack_02_F", EAST] call BIS_fnc_spawnVehicle;

**Comment by suitsy** [comment]
I will have a look at that function see what its doing. There is no issue with the vehicle spawning in the air its just not running/moving when it spawns.

**Comment by MitchDrage** [comment]
Not sure if you're still looking at this, but they fly around on mine. It seems a bit random, some hover for a bit, some start going forward straight away but in the end they all seem to start moving.
![107410_20170418175632_1](https://cloud.githubusercontent.com/assets/25337396/25120309/da39e25a-2460-11e7-81cf-75812abcacb3.png)

**Comment by suitsy** [comment]
fixed, added option to vehicles to add a flyinheight, added velocity so spawn in flying at speed.
