### ISSUE TITLE
Create Server-side ACE settings

### ISSUE THREAD

**Issue by LecksC** [LecksC/ASOR_Bugs#52]
Need to create a mission that just has all our modules and is set up to export ACE settings (I think from the editor).

**Comment by LecksC** [comment]
Needs to include spectator settings (see https://github.com/LecksC/ASOR_Bugs/issues/23 )

**Comment by suitsy** [comment]
Should this perhaps go in asor_main?

**Comment by LecksC** [comment]
I think asor_main should be extremely bare (basically just the CBA macros for full asor 'addon' setup). See
https://github.com/acemod/ACE3/tree/master/addons/main
and
https://github.com/CBATeam/CBA_A3/tree/master/addons/main

I think this should just go in asor_common (which requires ACE anyway).

**Comment by LecksC** [comment]
Actually.. it's a mission.. so it can't really go in any mod.

**Comment by suitsy** [comment]
Created and working
- [ ] Create medic buildings as custom objects with required code to make them medic buildings  
OR
- [ ] Make it so u can link buildings to the ASOR Settings module to make them a medic building
so we dont need the ACE Facility module. (last module remaining)

**Comment by suitsy** [comment]
- [x] added adv throw module to settings

**Comment by suitsy** [comment]
throw module info was there, was mod that was broken, fixed now with new version

**Comment by suitsy** [comment]
Done - now obsolete with ACE moving to CBA settings
