### ISSUE TITLE
Induction Slides

### ISSUE THREAD

**Issue by Heilidhe** [LecksC/ASOR_Bugs#53]
## Fix Slide Info

- [x] Correct Colours For SQUAD Layout - Red Fire-Team Has Blue Text/Blue Has Red Text
- [x] Fix ASOR Server Rules Slide is repeated twice
- [x] Remove 'RFL' from 'Basic Roles for new recruits' 
- [x] Fix "Examples" for PACES as there's two but one is not labelled as an "Example". 

More if found.

**Comment by suitsy** [comment]
_Correct Colours For SQUAD Layout - Red Fire-Team Has Blue Text/Red Has Blue Text_
this is actualy a paa conversion issue, bleeds the colours, might be able to correct but it will take some trial and error. 

 _Fix ASOR Server Rules Slide is repeated twice_
i think this is already fixed, I can send through the v2 of the powerpoint

**Comment by Heilidhe** [comment]
Maybe could give red fire team blue text in the slide then and vice versa, so that when it converts, it converts correctly or something.

Yeah think we were fixing it up hey. Think I had latest and was supposed to bounce it back (but forgot or something lol). Send it through when you get a chance.

**Comment by suitsy** [comment]
[ASOR_Induction_PP_v2.pptx](https://github.com/LecksC/ASOR_Bugs/files/927551/ASOR_Induction_PP_v2.pptx)

I have the psd file for the formations too, doesnt let me upload here, TBH though formation image needs redoing, happy to do down the track.

**Comment by Heilidhe** [comment]
@suitsy Yeah looks like Red Team is behind Blue Team in the Staggered Column (B before R? or Red Team always takes Point? ) 

Not too fussed about Formations/Colours - Can always clarify there, plus the purpose still serves to demonstrate whats going on (even if its slightly wrong).

- Included Couple Lines about FTX
- Clarified How to Speak When Dealing with medics (No "I", "Me" etc)
- Restructure of "Rules Page" cause the text was fkn crazy on the eyes. 
- Added Couple Lines about "Mission makers and Devs" always welcome.
- Slight Increases to the Size of Smaller text and a better fit to page on all slides.
- Final Touch On Slide (Briefly Touch on GS - HOW TO use Medical - Unconscious AI Demonstration)

**Comment by suitsy** [comment]
Red is on point as they have the Engineer

**Comment by Heilidhe** [comment]
Yeh thats what I thought. Powerpoint PSD is backwards (Blue's in front). Will check out fixing these soon.

**Comment by suitsy** [comment]
I think its how the paa's come up in game. I have the original PSD as in adobe graphic file and its right. The image as a jpg is fine, image as a paa is fine but in game on the slideshow its not.

**Comment by suitsy** [comment]
havent done the squad structure pic, forgot will do asap.

**Comment by Heilidhe** [comment]
Its no problem - not really priority on list rn

**Comment by suitsy** [comment]
I pushed the change for the missing comma, this may have been the error you experienced the second time? Just need to try reversing those colors on graphics now is that it @Heilidhe ?

**Comment by suitsy** [comment]
Slides updated, colors working. Closing this ticket!
