### ISSUE TITLE
FTX Virtual OBUA Course Activation

### ISSUE THREAD

**Issue by Brannac** [LecksC/ASOR_Bugs#56]
I went to do the Virtual OBUA course and when I activated it the course was still blue on the map and thought it wasn't spawning. I checked later in Zeus and the AI spawned but the zone didn't see that redfor AI were present in the zone and stayed Blue.

**Comment by Heilidhe** [comment]
Thanks - Resolved. 

Fixed in next release (probably sometime tomorrow).
