### ISSUE TITLE
Vehicle Selector CTD

### ISSUE THREAD

**Issue by Heilidhe** [LecksC/ASOR_Bugs#59]
## CTD Issues

Reports of vehicle Selector (Raven) when entering it causing a CTD. 

Not FTX related (happens on all maps).

Not sure if its specifically a VS issue. Sounds like a Vehicle Issue, but reports of them (A-10's) being spawnable in Zeus and being completely usable otherwise.

Will hunt for more info regarding this.

**Comment by LecksC** [comment]
Can you let me know exactly when it crashes (what you click) ?

Can confirm just loading into VR and spawning RHS planes crashes a lot (unless my system is suddenly unstable). This is without VS. 

I wasn't able to get it to crash while in the VS though.. only while flying (or more specifically.. crashing)

**Comment by LecksC** [comment]
accidently closed

**Comment by Heilidhe** [comment]
Yeah I haven't tested it yet personally, but will.

Hearing from multiple people the other day wanting to fly Raven on FTX that its either:
A) Getting into the VS Menu and clicking stuff
or
B) Clicking specific vehicles (A-10 to be exact).
Causing a CTD.

Sounds weird.
Must be RHS vehicles then.

**Comment by Heilidhe** [comment]
## CTD Report

@LecksC 
Both Raven Pilots tonight and the JTAC report:
(OneEyed, Towny, Axilla Hallux)
- CTD as SOON AS the Vehicle Selector Menu (for Raven) is Opened | Ace Interact with Sign, It opens the VS Interface, and as soon as the Interface loads, its a CTD. 

I believe my comments about specific vehicles was ill-informed/incorrect, so disregard.

## Further Report
Oxan
Brannac
Carnivore
Shivak 
All Report:

CTD after opening the VS (no buttons clicked).
Sometimes a delay and difference for the amount of time they see the UI for, but the same result occurs.
A CTD before being able to click anything and/or not being able to click anything before the CTD.

**Comment by Instant-Muffin** [comment]
Likely the A-10 Canopy as it's first on the list in the VS and isn't placable by Zeus. Unsure when it's used but may be when the jet is destroyed which may be why the A-10 would crash the server a while back (may still happen, haven't tested)

**Comment by suitsy** [comment]
Is this something like the SF boats, if you copy and past them with zues they are stuffed, there is some invisible ramp attached to them that doesnt copy.

**Comment by LecksC** [comment]
I did an hour of testing/trying to get it to crash today but couldn't. While spawning with VS/flying/ejecting from a bunch of jets, I had crashes while flying an F22 once (didn't try again since we don't use it anyway), and ejecting from the RHS A10 2/4 times, but never while opening/flicking through stuff in the VS.

Not really sure what to do with this. We could blacklist the junk (canopys, etc), but I have no hope of fixing the crash if I can't reproduce it.

This was on FTX on the ops server.

**Comment by Heilidhe** [comment]
Yeah not too sure Lecks. Don't think anyone has reported an issue with flying the particular jets (as I'm told they can place in Zeus and fly fine - at least on the Dedi).

They say its loading the VS interface thats causing a CTD (or at least thats where it happens).

My 2 cents would be to blacklist the A-10 canopy and any of that stuff that doesn't need to be in there (think there's like bombs as well?). Can do this if you let me know how.

**Comment by LecksC** [comment]
Blacklist should work the same as the gear selector (you can have faction-based, etc whitelists or just a blacklist). We've never actually used it though so I can't really guarantee it'll work as expected.. if not let me know.

**Comment by suitsy** [comment]
This is something we will need for the new campaign at some point so be good to know if its functioning.

**Comment by Heilidhe** [comment]
Nps, on it.

**Comment by Heilidhe** [comment]
## Updated

Removed A-10 Canopy, F-22 Canopy, Cruise Missile and Ejector Seat. Have a feeling this might of fixed the VS CTD.

A repo update and test will tell.

**Comment by Heilidhe** [comment]
The blacklist for this works too FYI. Will open up a ticket for the Organisation of Faction specific blacklists.

**Comment by Heilidhe** [comment]
FUCKING FIXED IT !!!!!!!!!!!!!!!!!!!!!!!!!!!! WOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.
Was fixed by removing Stupid Canopy and Seats/Missiles.
