### ISSUE TITLE
Changing loadout in VS changes the skin back to the default

### ISSUE THREAD

**Issue by MitchDrage** [LecksC/ASOR_Bugs#60]
Minor bug.
When changing the loadout of a vehicle in the VS, the selected skin is reverting to the default skin.
I believe it's changing the vehicle back to the default textureSources that is chosen by the VS.

As an example, after selecting M1A2 Sep v.1 and changing the sub-variant to the V11 model, if you then edit the loadout of the vehicle, it reverts the sub-variant back to the default which is the V22 model.

**Comment by LecksC** [comment]
When you say loadout, you mean cargo?

**Comment by MitchDrage** [comment]
yeah, cargo. Sorry

**Comment by MitchDrage** [comment]
Found a larger issue within the abrams config itself that was causing this.
The issue was that each callsign was created under the base vehicle class rather than the variant.
This has now been resolved.
