### ISSUE TITLE
Buzzing in Gear Selector

### ISSUE THREAD

**Issue by Brannac** [LecksC/ASOR_Bugs#62]
While in the Gear Selector in tonight's op there was a weird buzzing sound like a mic was left open while in the gear selector. Tried it again later away from my squad and had the same sound. Checked with some of my squad mates and they confirmed they had the sound as well. Not sure why this happened or if it can be fixed.

**Comment by LecksC** [comment]
It'll basically be something off the bottom left corner of the map (where the Gear Selector 'stage' is) making an noise, or possibly just wind or something in the area.

If it's a big problem I could mute the audio or something in the Gear Selector; do you think that's warranted? I've noticed various noises and stuff in there before but never really thought it was something worth fixing (arguably better than silence?).

**Comment by Brannac** [comment]
I'm not sure if its a big problem as people aren't in the gear selector too much, just wasn't sure if it should be brought up as the buzzing only existed in the gear selector and no where else.
Also wasn't sure if it may have been a bigger problem as multiple people had it.

**Comment by Heilidhe** [comment]
The buzzing seems to be from the RQ-11B Drone. Everyone can hear it as if its right next to them (in the GS) even if its half way across the map.

(It's pretty loud - not like a mic buzz - but not sure if it's always there every time the Raven is used in an OP).

**Comment by Brannac** [comment]
As far as I'm aware the Raven wasn't used on the op where I noticed the sound. It was just 1 Tacp and 2 x-ray.

**Comment by suitsy** [comment]
Drone was in use by Thumper. Def the drone noise, had it for 2 years, believe its an arma bug with displays.

**Comment by Heilidhe** [comment]
Yeh T-roy was using it when you reported it the other night @Brannac. I always thought it was an unfix-able bug tbh. Only solution I guess would be for Lecks to mute sound while in GS - or at least Effects sound? 

I personally don't mind it, but if muting sound won't effect  people's voices in Ts3 (I assume muting sound in GS will be effects volume) I guess it really depends on how many people are bothered by it.

**Comment by suitsy** [comment]
I will leave closing this to @LecksC but I dont think this is something that is easily fixed, pretty sure its arma related, displays etc. Muting sounds or anything like that isnt an option imo.

**Comment by LecksC** [comment]
Yeah gonna close this as it seems to be a bug with the drone, not VS (and I don't think it's a huge issue anyway).
