### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Heilidhe** [LecksC/ASOR_Bugs#63]
## Operation Jungle Sword 26/4

- [x] Verify and/or Fix:
Warning Message: No entry 'bin\config.bin/CfgMarkerColors.'.

- [x] Verify and/or fix:
19:04:11 Error in expression <Namespace setVariable [_variableName, + _value];
missionNamespace setVariable [_>
19:04:11   Error position: <_value];
missionNamespace setVariable [_>
19:04:11   Error Undefined variable in expression: _value
19:04:11 File task_force_radio\functions\fn_setSwSettings.sqf [TFAR_fnc_setSwSettings], line 31

19:04:11 Error in expression <tion = (_this select 2);
[_destination, _localSettings, true] call TFAR_fnc_setS>
19:04:11   Error position: <_localSettings, true] call TFAR_fnc_setS>
19:04:11   Error Undefined variable in expression: _localsettings
19:04:11 File task_force_radio\functions\fn_requestRadios.sqf [TFAR_fnc_requestRadios], line 32

Assumption for the Former to be an error in an @Addon we recently updated perhaps. 

The Latter, might've been a Personal TFAR issue.

**Comment by suitsy** [comment]
first one is probably a reference to a marker colour that doesnt exist, good luck finding that if thats all the info you have. not sure whats been updated that includes markers. I have updated a heap of stuff with the tracker but nothing on repo yet.

**Comment by Heilidhe** [comment]
Issues resolved.
