### ISSUE TITLE
Setup VS Blacklists - New Campaign 

### ISSUE THREAD

**Issue by Heilidhe** [LecksC/ASOR_Bugs#65]
Organise a layout template, even if there is not yet planned blacklists for specific factions.

**Comment by suitsy** [comment]
setup a vehicle_blacklist.hpp (currently only in berko > army > 12th as a test) that will make up the faction vehicle blacklists, it will need an update though from @LecksC to work so waiting on that to proceed with vehicle list

**Comment by suitsy** [comment]
Created a global vehicle whitelist that is created automatically from vehicles enabled in config. located in asor_factions/common/vehicle_list.hpp

this may have to become a per faction file if we need to add other vehicles not in the config as per the weapon lists.

@LecksC going to make updates to vehicle selector to make it a whitelist only, so only vehicles available will be those listed in this vehicle list.

- [ ] vehicle selector updated to whitelist

**Comment by LecksC** [comment]
Both gear and vehicle selector now support either a global blacklist or a global whitelist.

Vehicles will show if they're either in the whitelist, in cargo, and/or in a matching 'specific' whitelist.

Gear will show if it's in the whitelist or a matching 'specific' whitelist.

Backwards compatible with current blacklist.

https://github.com/LecksC/ASOR/commit/6590b23c61738e62214b2f7242e73dba9988d2ce

**Comment by suitsy** [comment]
Awesome thanks lecks, I will finalise the lists this weekend, once this is done its just testing and adjusting and gtg.

- [x] whitelist setup

**Comment by suitsy** [comment]
Vehicle whitelist is setup for all factions, using a common file in asor_factions/common to build a generic vehicle whitelist for each faction based on the faction config. If we need to add alternate vehicles not included in the config for specific factions will need to move this to faction directories in asor_factions. 

- [x] vehicle whitelist working and tested

**Comment by suitsy** [comment]
- made the vehicle whitelists a per faction list so we can add more vehicles per faction

all thats left to do is add any vehicles we need to the lists, closing ticket as done.
