### ISSUE TITLE
Ammo Crates for Factions

### ISSUE THREAD

**Issue by suitsy** [LecksC/ASOR_Bugs#66]
Need to create ammo crates for each faction, inherit where gear the same.

Berkovetus
- [x] asor_army_12mountain
- [x] asor_police_varcolac
- [x] asor_rebel_bng
- [x] asor_sf_strigoi

Russian
- [x] asor_army_vdv
- [x] asor_rebel_voshod
- [x] asor_spetsnaz_vympel
- [x] asor_spetsnaz_zaslon

China
- [x] pla

Blufor
- [x] asor
- [x] sasr

**Comment by suitsy** [comment]
creating initial ammo crates automatically by extracting config ammo. File is located in individual faction folders so additional ammo and items can be added per faction if needed.

atm only creating boxes for
infantry air and ground
medical air and ground

Possible issue with other kit in boxes, may need to blank it first.

**Comment by suitsy** [comment]
Set the ammo crates up as a generic file in each faction folder of asor_factions that builds the ammo boxes from the faction config. Left it as a per faction file so we can add custom lines or change the type of box it comes in as needed. 

ie. Russian ammo box for Russian factions. Will close this ticket once tested.

- [x] Ammo boxes tested and working as required.

**Comment by suitsy** [comment]
Potential issue is when we use dual factions XRAY pilot will only have access to his factions ammo box. Will need to make all GROUP boxes available to all factions in the list and ensure they are named accurately to tell the difference between them.

- [x] Ammo boxes names correctly
- [ ] FACTION ammo boxes available to GROUP

**Comment by suitsy** [comment]
1. Need to create ammo boxes at group level.
2. Include side boxes for each faction in vehicle selector.

**Comment by LecksC** [comment]
I'm not sure if the VS is working as expected, but atm we have all infantry ammo boxes available; so the only issue is no vehicle ammo/fuel/repair.

Not sure what you mean by 'side boxes'.

The only other (sort of related) problem we had is that light chopper can't slingload, so slingloading will have to be done in a Mi8 which handles similar to a chinook (resupps will be a lot slower/harder, and resupps + landings won't be feasible as often). Not really an issue but worth keeping in mind.

**Comment by suitsy** [comment]
ok if they all displaying thats what i wanted i guess, so xray can re-supp multiple factions if needed. Thats what I meant by side, all opfor factions ammo boxes etc.
I added ammo/fuel today.

yeah spew about the light heli no slingload.

**Comment by suitsy** [comment]
- added the vehicle ammo and fuel to the selector whitelist (available to all)

Other than adding vehicles we need per faction I think this is closed and gtg
