### ISSUE TITLE
Vehicle Selector - Synced objects breaking when ticking vehicle types, etc

### ISSUE THREAD

**Issue by LecksC** [LecksC/ASOR_Bugs#69]
Currently need to resync after ticking boxes for additional vehicle types (possibly other properties). Otherwise it shows as 'any' in the menu and doesn't work.

**Comment by suitsy** [comment]
@LecksC does something need to happen with the attributesChanged3DEN to perhaps update something with this? Ticking a checkbox changes a variable, can probably run something to update whatever needs to be updated perhaps?

Sorry havent looked at detail.

**Comment by LecksC** [comment]
I don't really understand why it falls apart when you change an attribute (it shouldn't effect the syncing unless maybe the hidden controls are blanking out the values or something).

I guess a workaround would be to run asor_objects_fnc_onConnectionChanged3DEN on the attributesChanged3DEN event as well.

As for how it works, the above function effectively updates a textbox with like [45,323,99] for all the synced objects in ASOR_SyncedObjects, and another text box on all the synced objects (ASOR_3DENID) to one of those numbers (numbers are based on get3DENEntityID). The latter is used to created a missionnamespace variable like ASOR_3DENObject45 so you can retreive them based on the SyncedObjects array.

I put it in anyway.. can't do any harm other than maybe a bit of lag when you edit attributes (including possibly dragging stuff around)

https://github.com/LecksC/ASOR/commit/9cf94ab664deff02f61588024219c5188108c275

Haven't tested yet.

**Comment by LecksC** [comment]
Don't think this is still an issue?

**Comment by suitsy** [comment]
I havent noticed it but dont often place a selector from scratch, tend to copy an old one in.

**Comment by Heilidhe** [comment]
No longer an issue, or not identified.
