### ISSUE TITLE
Error/Observation Report 16/6

### ISSUE THREAD

**Issue by Heilidhe** [LecksC/ASOR_Bugs#71]
## VERIFY

Verify and tick if the issue is known - just noting in case they haven't been detected.

- [x] VERIFY: Voshod's URAL AAA giving Warning Message: Bad vehicle type asor_rebel_voshod_crew
Cannot create non-ai vehicle asor_rebel_voshod_crew

## OBSERVATIONS

If known, or are not oversights then ignore. Noticed and reporting.

- [x] VERIFY: 12 Mountain Division, Varcolac & Strigoi have Two "Helicopter Sections". 

- [x] VERIFY:  Groups (F2) has a lower case section called 'asor', containing what looks to be "ASLAVS + AT" but no AI.

**Comment by suitsy** [comment]
ASOR group is known. To many places to change items at this point.

**Comment by suitsy** [comment]
Fixed crew error, AAA truck was being created under armour, voshod dont have armour or crew units so no crew was available. Moved AAA truck to truck config.

**Comment by suitsy** [comment]
This isnt confirmed but will to bet the helicopter dual issues is RHS naming the category 'Helicopters' for their helicopters and either vanilla or another mod using the vanilla group 'Helicopter'. Could override the sub-category of one or the other too fix.

**Comment by Heilidhe** [comment]
Updated as of 22/6

## Vehicle Name

- [x] BNG's BTR-60 looks to be incorrectly named as a "BRDM2". BNG's "Armed BRDM2" looks to be named as a BTR-60.

**Comment by suitsy** [comment]
fixed btr/brdm naming

**Comment by suitsy** [comment]
Closing, not much to do about the two helicopter menus, not worth fixing.
