### ISSUE TITLE
Safehouse System

### ISSUE THREAD

**Issue by suitsy** [LecksC/ASOR_Bugs#72]
Ability to deploy a safehouse that has a Laptop and Gear Selector. Also creates a 'move-to' point for the squad that deploys the safehouse which will be accessible from the QRF point.

SAFEHOUSE
Object required to be carried to deploy safehouse.
Move-To location.
Tables, Laptop, Satephone, GS Box

LAPTOP
Ability to send SMS messages to command.
Ability to run other 'programs' to gather intel.

**Comment by Woodsylord** [comment]
If we can get SMS functioning, would be useful having a picture or video function. Could use something similar to the PIP from the UAV, with the camera as the UAV Camera and the recipient getting the pic or video? That way covert teams could sent data back to strike elements.

**Comment by suitsy** [comment]
- [x] add SH object to MISC items on GS
- [x] fix markers to be global not local for SH spawn
- [ ] create a crash recover type function for moving to SH
- [ ] fix actions on SH to be under one easy accessible menu
- [x] fix packup function, removing of kit from SH array and delete/moving of SH marker

**Comment by suitsy** [comment]
Updated. Still need to sort out actions menu and teleport function.

**Comment by suitsy** [comment]
Done, @Instant-Muffin also made the rally point system from this.
