### ISSUE TITLE
Radio Jammer

### ISSUE THREAD

**Issue by Woodsylord** [LecksC/ASOR_Bugs#73]
Attempting to build a TFAR radio Jammer backpack. 

Idea is to take a pack we are not using, or meld the Bussole and an Assault pack similar to the ASOR LR radios and add a script similar to: http://www.armaholic.com/page.php?id=32660 

Intent is to have a jammer that either an RP player or AI could have that could disrupt our comms should we need to. In theory, could also be used against IEDs if it worked with the AE modules. 

Essentially Woodsy learning to do stuff.

**Comment by Woodsylord** [comment]
Seems that there has been some discussion on this: https://gh.com/michail-nikolaev/task-force-arma-3-radio/issues/1231

https://www.youtube.com/watch?v=inCAffSquP0&feature=youtu.be

**Comment by suitsy** [comment]
Irony has a script that does this well
