### ISSUE TITLE
Add capacity to civ clothing

### ISSUE THREAD

**Issue by LecksC** [LecksC/ASOR_Bugs#75]
Think it's worth doing this to work around the fact they can't wear vests, and it looks dumb with everyone wearing a backpack? I think most rifles still won't go in them because they're configed to only go in backpacks, but at least they could carry a pistol and a bit of ammo.

**Comment by suitsy** [comment]
Yeah, its cold, puffy jackets?

**Comment by Heilidhe** [comment]
I'd imagine we'd do this in asor_fixes?

**Comment by Woodsylord** [comment]
There is an invisible backpacks mod that may be of use: http://www.armaholic.com/page.php?id=31872

**Comment by suitsy** [comment]
No longer required, closing.
