### ISSUE TITLE
No VDV Ammo box

### ISSUE THREAD

**Issue by LecksC** [LecksC/ASOR_Bugs#77]
At least not in the vehicle selector.

Last night used vympel, the only complaint for which was missing 'bigger' rpg rockets.

**Comment by suitsy** [comment]
Last night we were VDV? Was it last night VDV box wasnt there or was it when we were playing as Vympel the night before?
I chose a random rocket to put in the crates, no probs to change the type if someone lets me know what type they want.

**Comment by LecksC** [comment]
Yeah, we were VDV, but we couldn't get/see the VDV box so we got Vympel instead.

**Comment by Woodsylord** [comment]
I'll grab thr rocket name soonish. Won't be the bit one that does all tanks but the model below. Could even include the RPG backpack carroer filled with three that they can just grab and rock n' roll.

_Sent from my Samsung SM-G930F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by suitsy** [comment]
Not sure what the issue is here, the box is in zues and is definitely in the config and whitelist the same as all other boxes. Maybe it was just missed? Need to check if its definitely not available.

**Comment by suitsy** [comment]
Fixed, had error in whitelist class names
