### ISSUE TITLE
Figure Out Why #missions takes 2mins

### ISSUE THREAD

**Issue by suitsy** [LecksC/ASOR_Bugs#80]
When logged in as admin it takes a good 2 mins to get to the mission select screen.

I have tried moving all old missions to a separate drive in case it was looking through all of them even missions in sub folders but no change. 

Could it be just any arma thing?

**Comment by LecksC** [comment]
test

**Comment by suitsy** [comment]
test2

**Comment by suitsy** [comment]
Reading on this it seems when a player connects the server reads through all the desc.ext's so having lots of them can be a issue, a mission with an error in one is probably the cause of the delay.

**Comment by suitsy** [comment]
Removed all missions and #missions is instant now so lots of missions is def the cause of the delay. Closed.
