### ISSUE TITLE
Error on Vehicle Selector Attributes

### ISSUE THREAD

**Issue by suitsy** [LecksC/ASOR_Bugs#83]
18:08:46 Error in expression <object>
18:08:46   Error position: <object>
18:08:46   Error Undefined variable in expression: object
18:08:46 Error in bin\config.bin/CfgVehicles/ASOR_vehicle_selector_infostand/Attributes/ASOR_SyncedObjects.condition
18:08:46 Error in expression <object>
18:08:46   Error position: <object>
18:08:46   Error Undefined variable in expression: object
18:08:46 Error in bin\config.bin/CfgVehicles/ASOR_vehicle_selector_infostand/Attributes/ASOR_3DENId.condition
18:08:46 Error in expression <object>
18:08:46   Error position: <object>
18:08:46   Error Undefined variable in expression: object
18:08:46 Error in bin\config.bin/CfgVehicles/asor_rangecontrol_infostand/Attributes/ASOR_SyncedObjects.condition
18:08:46 Error in expression <object>
18:08:46   Error position: <object>
18:08:46   Error Undefined variable in expression: object
18:08:46 Error in bin\config.bin/CfgVehicles/asor_rangecontrol_infostand/Attributes/ASOR_3DENId.condition
18:08:46 Error in expression <object>
18:08:46   Error position: <object>
18:08:46   Error Undefined variable in expression: object
18:08:46 Error in bin\config.bin/CfgVehicles/ASOR_vehicle_selector_helipad1/Attributes/ASOR_SyncedObjects.condition

**Comment by suitsy** [comment]
This is from asor_objects

`condition = "object";`

P:\ASOR\asor_objects\configs\asor_vehicle_selector.hpp

**Comment by LecksC** [comment]
hmm.. that should be correct according to docs:
https://community.bistudio.com/wiki/Eden_Editor:_Configuring_Attributes

**Comment by LecksC** [comment]
maybe their example is wrong.. 

> To make an attribute available for all objects, use: `condition = "1";`

**Comment by suitsy** [comment]
yeah 1 would be true
the errors only been coming up since the patch and everything still seems to work so its defaulting to true anyhow

**Comment by suitsy** [comment]
ah yeah it says see the table below, which is:

objectBrain | Object | Object with simulation "soldier" or "UAVpilot"
-- | -- | --
objectControllable | Object | Object with simulation "soldier"
objectAgent | Object | Object with non-empty agentTasks[], i.e., animals
objectVehicle | Object | Vehicle which can be boarded
objectSimulated | Object | Object which is simulated (e.g., falls down when in the air)
objectDestructable | Object | Indestructible object, i.e., when destrType config property set not DestructNo
logicModule | Logic | Logic which is a module (vehicleClass config property is "Modules")
objectHasInventoryCargo | Object | All objects which have an openable inventory

**Comment by LecksC** [comment]
Yeah, none of them fit the helipad though, so i think it just needs to be "1".

**Comment by suitsy** [comment]
i just have "true" in all mine that dont have a calc but yeah pretty sure 1 = true anyway hey

**Comment by LecksC** [comment]
yeah mikeros tools will be changing "true" to 1

**Comment by suitsy** [comment]
fixed, pushed
