### ISSUE TITLE
GS Not Displaying ACE Action After Patch 

### ISSUE THREAD

**Issue by suitsy** [LecksC/ASOR_Bugs#84]
Signs still seem to work but the pre-made GS crates do not or intermittently work only.

**Comment by suitsy** [comment]
Tried to sus this out but when i go into FTX all the GS's work for me. Used the command to add it to another box and worked fine.

**Comment by suitsy** [comment]
Loaded the mission where its not working, have no idea why its not. Can place ones with ZUES and they work and they are def the right boxes used ("asor_gear_selector_box_west").

See what happens tonight i guess.

**Comment by suitsy** [comment]
Wonder if this is because they inherit from `AmmoCrates_NoInteractive_Large`, maybe they have changed that in some way that it bugs the actions. This only seems to happen on the server.

**Comment by Instant-Muffin** [comment]
To be clear on the Zeus bit, they work on the server for the player that places them down but not for anyone else. They also no longer work if you go back to the lobby and come back in.
Not sue why the update would have caused that though.

**Comment by suitsy** [comment]
yeah just sounds like a locality issue but the code is in the init of the object which runs on everyone including jip so doesnt make sense

**Comment by Instant-Muffin** [comment]
Have we tried the other gear selector objects? Like the east one?

**Comment by suitsy** [comment]
Nah I havent, everytime i try to test it, it works. That would tell us if its the object though.

**Comment by suitsy** [comment]
Updated actions to ACE Config, need to check works dedicated in op.

**Comment by suitsy** [comment]
Fixed and working.
