### ISSUE TITLE
AE: Reverse Suspend Module Option

### ISSUE THREAD

**Issue by LecksC** [LecksC/ASOR_Bugs#9]
<a href="https://github.com/suitsy"><img src="https://avatars3.githubusercontent.com/u/13358761?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [suitsy](https://github.com/suitsy)**
_Thursday Dec 03, 2015 at 04:30 GMT_
_Originally opened as https://github.com/LecksC/ASOR/issues/4_

----

Add feature to allow suspend module to disable zones when activated.

**Comment by suitsy** [comment]
Added capability with new Control Module, closed.
